Repository crashkonijn/GOAP, pull requests merged in 2023-12, with the labels that each got.

#127 DebugGraph conflict fix
  Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/NodeViewerEditorWindow.cs
Labels: bug

#132 Docs: Added tutorial references
  Package/Documentation/Introduction/GettingStarted.md
  README.md
Labels: docs

#134 Feature: improved auto-fix when generating duplicate files
  Demo/Assets/CrashKonijn/GOAP/Test/Actions/VeryUniqueAction.cs
  Demo/Assets/CrashKonijn/GOAP/Test/Actions/VeryUniqueAction.cs.meta
  Demo/Assets/CrashKonijn/GOAP/Test/Capabilities/TestCapability.asset
  Demo/Assets/CrashKonijn/GOAP/Test/Goals/TestGoal.cs
  Demo/Assets/CrashKonijn/GOAP/Test/Goals/TestGoal.cs.meta
  Demo/Assets/CrashKonijn/GOAP/Test/TargetKeys/AnotherTargetKey.cs
  Demo/Assets/CrashKonijn/GOAP/Test/TargetKeys/AnotherTargetKey.cs.meta
  Demo/Assets/CrashKonijn/GOAP/Test/WorldKeys/TestKey.cs
  Demo/Assets/CrashKonijn/GOAP/Test/WorldKeys/TestKey.cs.meta
  Package/Editor/CrashKonijn.Goap.Editor/Elements/ClassRefField.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/SensorList.cs
  Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/CapabilityConfigScriptableEditor.cs
  Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/GeneratorEditor.cs
  Package/Runtime/CrashKonijn.Goap.Support.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/ClassGenerator.cs.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Templates.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Templates/action.template.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Templates/goal.template.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Templates/multi-sensor.template.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Templates/target-key.template.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Templates/world-key.template.meta
  Package/Runtime/CrashKonijn.Goap.Support/com.crashkonijn.goap.support.asmdef
  Package/Runtime/CrashKonijn.Goap.Support/com.crashkonijn.goap.support.asmdef.meta
  Package/Runtime/CrashKonijn.Goap/ClassScanner.cs
  Package/Runtime/CrashKonijn.Goap/Extensions.cs
  Package/Runtime/CrashKonijn.Goap/Generators.meta
  Package/Runtime/CrashKonijn.Goap/Generators/ClassGenerator.cs
  Package/Runtime/CrashKonijn.Goap/Generators/ClassGenerator.cs.meta
  Package/Runtime/CrashKonijn.Goap/Generators/Templates.meta
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/action.template
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/action.template.meta
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/goal.template
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/goal.template.meta
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/multi-sensor.template
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/multi-sensor.template.meta
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/target-key.template
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/target-key.template.meta
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/world-key.template
  Package/Runtime/CrashKonijn.Goap/Generators/Templates/world-key.template.meta
  Package/Runtime/CrashKonijn.Goap/ScriptIdValidator.cs
  Package/Runtime/CrashKonijn.Goap/Scriptables/GeneratorScriptable.cs
Labels: bug, enhancement
