Repository crashkonijn/GOAP, pull requests merged in 2023-11, with the labels that each got.

#95 chore: Added release-drafter
  .github/workflows/pull-request-labeler.yml
  .github/workflows/release-drafter.yml
Labels: chore

#96 Create release-drafter.yml config
  .github/release-drafter.yml
Labels: chore

#97 feat: added update-package workflow
  .github/workflows/update-package.yml
  Package/Samples~/default/.gitkeep
  Package/package.json
Labels: enhancement

#103 Added docs about world state
  Package/Documentation/SUMMARY.md
Labels: docs

#104 Fix: demo path
  Package/package.json
Labels: bug

#112 Fix: Goal completion not clearing goal
  Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
  Package/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs
  Package/Runtime/CrashKonijn.Goap/Interfaces/IAgent.cs
Labels: bug

#113 docs: Update GettingStarted.md with missing using
  Package/Documentation/Introduction/GettingStarted.md
Labels: docs

#115 Feature: working agent type
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/SettingsBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/SimpleAgentBrain.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/SimpleHungerBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/SimpleHungerBehaviour.cs.meta
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/TextBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/EatAppleAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/AgentTypes.meta
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/AgentTypes/SimpleAgent.asset
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/AgentTypes/SimpleAgent.asset.meta
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Capabilities/HealthCapability.asset
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Capabilities/HealthCapability.asset.meta
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Capabilities/WanderCapability.asset
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Scenes/SimpleDemoScene.unity
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Sensors/Multi/AppleSensor.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Sensors/World/IsHungrySensor.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Prefabs/Agent.prefab
  Demo/UserSettings/Layouts/default-2022.dwlt
  Package/Editor/CrashKonijn.Goap.Editor/Elements/ActionList.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/CapabilityActionElement.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/CapabilityConditionElement.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/CapabilityEffectElement.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/CapabilityGoalElement.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/CapabilitySensorElement.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/ClassRefField.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/ConditionList.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/EffectList.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/GoalList.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/SensorList.cs
  Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/CapabilityConfigScriptableEditor.cs
  Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/GeneratorEditor.cs
  Package/Runtime/CrashKonijn.Goap.Core/Enums/ClassRefStatus.cs
  Package/Runtime/CrashKonijn.Goap.Core/Enums/ClassRefStatus.cs.meta
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentTypeConfig.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IClassRef.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IClassRef.cs.meta
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Extensions.cs
  Package/Runtime/CrashKonijn.Goap.Support/Generators/Extensions.cs.meta
  Package/Runtime/CrashKonijn.Goap.Support/Loaders.meta
  Package/Runtime/CrashKonijn.Goap.Support/Loaders/ClassScanner.cs.meta
  Package/Runtime/CrashKonijn.Goap.Support/com.crashkonijn.goap.support.asmdef
  Package/Runtime/CrashKonijn.Goap/ClassScanner.cs
  Package/Runtime/CrashKonijn.Goap/ClassScanner.cs.meta
  Package/Runtime/CrashKonijn.Goap/Configs/GoalConfig.cs
  Package/Runtime/CrashKonijn.Goap/Configs/MultiSensorConfig.cs
  Package/Runtime/CrashKonijn.Goap/Configs/MultiSensorConfig.cs.meta
  Package/Runtime/CrashKonijn.Goap/Extensions.cs
  Package/Runtime/CrashKonijn.Goap/Scriptables/AgentTypeScriptable.cs
  Package/Runtime/CrashKonijn.Goap/Scriptables/CapabilityConfigScriptable.cs
  Package/Runtime/CrashKonijn.Goap/Scriptables/GeneratorScriptable.cs
  Package/Runtime/CrashKonijn.Goap/Scriptables/GeneratorScriptable.cs.meta
  Package/Runtime/CrashKonijn.Goap/com.crashkonijn.goap.asmdef
Labels: enhancement

#121 Feature: Added IActionRunState, split Action.End into Stop and Complete
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/CreateItemAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/EatAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/GatherItemAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/HaulItemAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/PickupItemAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Actions/WanderAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Shared/Actions/WanderAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/EatAppleAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/PickupAppleAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/PluckAppleAction.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/WanderAction.cs
  Demo/UserSettings/Layouts/default-2022.dwlt
  Package/Runtime/CrashKonijn.Goap.Core/Enums/ActionRunState.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAction.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IActionRunState.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgent.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentEvents.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentTypeEvents.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IGoapEvents.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/ITimer.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/ActionBase.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/ActionRunner.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/ActionRunner.cs.meta
  Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/AgentEvents.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/AgentTypeEvents.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/GoapEvents.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/Timer.cs
  Package/Runtime/CrashKonijn.Goap/Classes/Controllers/ProactiveController.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/ActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/ActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/CompletedActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/CompletedActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/ContinueActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/ContinueActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/ContinueOrResolveActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/ContinueOrResolveActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/StopActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/StopActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/WaitActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/WaitActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/WaitThenCompleteActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/WaitThenCompleteActionRunState.cs.meta
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/WaitThenStopActionRunState.cs
  Package/Runtime/CrashKonijn.Goap/Classes/RunStates/WaitThenStopActionRunState.cs.meta
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/ActionRunnerTests.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/ActionRunnerTests.cs.meta
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentBehaviourTests.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/Classes/TestAction.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/Data/Action.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/ProactiveControllerTests.cs
Labels: enhancement

#123 Feature: Improved handling of world data
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Goap/Actions/EatAppleAction.cs
  Package/Editor/CrashKonijn.Goap.Editor/Drawers/ObjectDrawer.cs
  Package/Editor/CrashKonijn.Goap.Editor/Elements/ListElementBase.cs
  Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/NodeDrawer.cs
  Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/NodesDrawer.cs
  Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/WorldDataDrawer.cs
  Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/AgentEditor.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgent.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IAgentType.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/ILocalWorldData.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/ISensorRunner.cs
  Package/Runtime/CrashKonijn.Goap.Core/Interfaces/IWorldData.cs
  Package/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs
  Package/Runtime/CrashKonijn.Goap/Classes/AgentType.cs
  Package/Runtime/CrashKonijn.Goap/Classes/AgentTypeFactory.cs
  Package/Runtime/CrashKonijn.Goap/Classes/Runners/AgentTypeJobRunner.cs
  Package/Runtime/CrashKonijn.Goap/Classes/Runners/SensorRunner.cs
  Package/Runtime/CrashKonijn.Goap/GlobalWorldData.cs
  Package/Runtime/CrashKonijn.Goap/LocalWorldData.cs
  Package/Runtime/CrashKonijn.Goap/WorldDataBase.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentBehaviourTests.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentTypeJobRunnerTests.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/SensorRunnerTests.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/WorldDataBaseTests.cs
Labels: enhancement

#124 Feature: Improved editor readability (especially in light mode)
  Package/Editor/CrashKonijn.Goap.Editor/NodeViewer/Drawers/NodeDrawer.cs
  Package/Editor/CrashKonijn.Goap.Editor/Styles/Generic.uss
  Package/Editor/CrashKonijn.Goap.Editor/Styles/NodeViewer.uss
  Package/Editor/CrashKonijn.Goap.Editor/Styles/NodeViewer_2022.uss
Labels: enhancement
