Repository crashkonijn/GOAP, pull requests merged in 2025-03, with the labels that each got.

#336 Feature: pause agent. Fixes #329
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Behaviours/AgentMoveBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Behaviours/AnimationBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Complex/Behaviours/ComplexHungerBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Shared/Behaviours/AgentMoveBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Shared/Behaviours/AnimationBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/AgentMoveBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/AnimationBehaviour.cs
  Demo/Assets/CrashKonijn/GOAP/Demos/Simple/Behaviours/SimpleHungerBehaviour.cs
  Demo/Assets/Docs/GettingStarted/Behaviours/AgentMoveBehaviour.cs
  Package/Documentation/Introduction/Setup.md
  Package/Editor/CrashKonijn.Goap.Editor/TypeDrawers/AgentEditor.cs
  Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IActionReceiver.cs
  Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IAgent.cs
  Package/Runtime/CrashKonijn.Agent.Core/Interfaces/IAgentEvents.cs
  Package/Runtime/CrashKonijn.Agent.Runtime/AgentBehaviour.cs
  Package/Runtime/CrashKonijn.Agent.Runtime/AgentEvents.cs
  Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Controllers/ProactiveController.cs
  Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Controllers/ReactiveController.cs
  Package/Runtime/CrashKonijn.Goap.Runtime/Classes/Runners/AgentTypeJobRunner.cs
  Package/Tests/CrashKonijn.Goap.Tests/UnitTests/AgentBehaviourTests.cs
Labels: bug, enhancement

#339 Fix: Minor docs mistake. Fixes #338
  Package/Documentation/Examples/Complex.md
Labels: bug

#341 Fix: Creating an agent outside of IdleTargetSensor bounds would result in an endless loop
  Demo/Assets/Docs/GettingStarted/Sensors/IdleTargetSensor.cs
  Demo/Assets/Docs/GettingStarted/Sensors/PearSensor.cs
  Package/Documentation/Introduction/Pears.md
  Package/Documentation/Introduction/Setup.md
Labels: bug

#342 Enhancement: Allow AgentTypeBehaviour to be more easily subclassed
  Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/AgentTypeBehaviour.cs
Labels: enhancement

#343 Enhancement: GoapActionBehaviour IsInRange overriding
  Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionBase.cs
Labels: enhancement

#345 Feature: Rabbit Logger support
  Package/Runtime/CrashKonijn.Agent.Core/Interfaces/ILogger.cs
  Package/Runtime/CrashKonijn.Agent.Core/com.crashkonijn.agent.core.asmdef
  Package/Runtime/CrashKonijn.Agent.Runtime/AgentBehaviour.cs
  Package/Runtime/CrashKonijn.Agent.Runtime/AgentLogger.cs
  Package/Runtime/CrashKonijn.Agent.Runtime/LoggerBase.cs
  Package/Runtime/CrashKonijn.Agent.Runtime/com.crashkonijn.agent.runtime.asmdef
  Package/Runtime/CrashKonijn.Goap.Resolver/com.crashkonijn.goap.resolver.asmdef
  Package/Runtime/CrashKonijn.Goap.Runtime/Behaviours/GoapActionProvider.cs
  Package/Runtime/CrashKonijn.Goap.Runtime/Classes/GoapAgentLogger.cs
Labels: enhancement

#346 Docs: Added extra info about generator
  Package/Documentation/General/Generator.md
  Package/Documentation/Introduction/Setup.md
Labels: docs
